version: '3.8'
services:
  postgres:
    image: postgres:16.0
    container_name: FaithSafeDB
    environment:
      POSTGRES_DB: faithsafeapi
      POSTGRES_USER: ${DATABASE_USERNAME:-root}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-root}
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: FaithSafeWebAPI
    environment:
      HOST_NAME: ${HOST_NAME:-postgres}
      DATABASE_USERNAME: ${DATABASE_USERNAME:-root}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-root}
    ports:
      - "8080:8080"
    depends_on:
      - postgres
