version: '3.8'
services:
  postgres:
    image: postgres:16.0
    container_name: FaithSafeDB
    environment:
      POSTGRES_DB: faithsafe-api
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: FaithSafeWebAPI
    ports:
      - "8080:8080"
    depends_on:
      - postgres
